INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (1, 'kevin', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (2, 'Jin', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (3, 'mountain du', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (4, 'モカ妹紅', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (5, 'Pinacola', 'UCSD', 25);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (6, 'Ste1la', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (7, 'oojoo', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (8, 'Iconclastic', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (9, 'zhcough', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (10, 'gzy', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (11, 'ZGMF-X20A', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (12, 'hikawasayo', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (13, 'Peter', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (14, 'Weber', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (15, 'edmund', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (16, 'dongdong', 'UCSD', 0);
INSERT INTO ucsd_mahjong.player (id, name, school, total_score) VALUES (17, 'Jonathan Yang', 'UCSD', 0);
